### ISSUE TITLE
lsp crash on didOpen single file without a workspace folder

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#219]
Opening a single file without a workspace folder will initialize with `rootUri = null`. Currently, it is not handled so that the lsp server will crash.

```
[2020-02-26 10:03:01.835] connection type: tcp at  62191

[2020-02-26 10:03:01.853] connected

[2020-02-26 10:03:02.503] received:  Content-Length: 2564

[2020-02-26 10:03:02.541] received payload.

[2020-02-26 10:03:02.541] handling request:  initialize

[2020-02-26 10:03:02.541] initialization config:  {
  "processId": 56722,
  "rootPath": null,
  "rootUri": null,
  "capabilities": {
    "workspace": {
      "applyEdit": true,
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ],
        "failureHandling": "textOnlyTransactional"
      },
      "didChangeConfiguration": {
        "dynamicRegistration": true
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "symbol": {
        "dynamicRegistration": true,
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": true
      },
      "configuration": true,
      "workspaceFolders": true
    },
    "textDocument": {
      "publishDiagnostics": {
        "relatedInformation": true
      },
      "synchronization": {
        "dynamicRegistration": true,
        "willSave": true,
        "willSaveWaitUntil": true,
        "didSave": true
      },
      "completion": {
        "dynamicRegistration": true,
        "contextSupport": true,
        "completionItem": {
          "snippetSupport": true,
          "commitCharactersSupport": true,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "deprecatedSupport": true,
          "preselectSupport": true
        },
        "completionItemKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25
          ]
        }
      },
      "hover": {
        "dynamicRegistration": true,
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "signatureHelp": {
        "dynamicRegistration": true,
        "signatureInformation": {
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "definition": {
        "dynamicRegistration": true,
        "linkSupport": true
      },
      "references": {
        "dynamicRegistration": true
      },
      "documentHighlight": {
        "dynamicRegistration": true
      },
      "documentSymbol": {
        "dynamicRegistration": true,
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        }
      },
      "codeLens": {
        "dynamicRegistration": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "onTypeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "documentLink": {
        "dynamicRegistration": true
      },
      "typeDefinition": {
        "dynamicRegistration": true,
        "linkSupport": true
      },
      "implementation": {
        "dynamicRegistration": true,
        "linkSupport": true
      },
      "colorProvider": {
        "dynamicRegistration": true
      },
      "foldingRange": {
        "dynamicRegistration": true,
        "rangeLimit": 5000,
        "lineFoldingOnly": true
      },
      "declaration": {
        "dynamicRegistration": true,
        "linkSupport": true
      }
    }
  },
  "trace": "off",
  "workspaceFolders": null
}

[2020-02-26 10:03:02.555] deliver:  ["Response", "Message", "R6"]

[2020-02-26 10:03:02.776] received:  Content-Length: 52

[2020-02-26 10:03:02.794] received payload.

[2020-02-26 10:03:02.794] handling notification:  initialized
[2020-02-26 10:03:02.794] on_initialized

[2020-02-26 10:03:02.795] internal error: Error: missing value where TRUE/FALSE needed
Call: if (is_package(project_root)) {
    source_dir <- file.path(project_root, "R")
    files <- list.files(source_dir)
    for (f in files) {
        logger$info("load ", f)
        path <- file.path(source_dir, f)
        uri <- path_to_uri(path)
        doc <- Document$new(uri, NULL, readr::read_lines(path))
        self$workspace$documents$set(uri, doc)
        self$text_sync(uri, document = doc, parse = TRUE)
    }
    deps <- tryCatch(desc::desc_get_deps(project_root), error = function(e) NULL)
    if (!is.null(deps)) {
        packages <- Filter(function(x) x != "R", deps$package[deps$type == 
            "Depends"])
        self$workspace$load_packages(packages)
    }
}
Stack trace:
1: dispatch(self, params)

[2020-02-26 10:03:02.796] received:  Content-Length: 169

[2020-02-26 10:03:02.807] received payload.

[2020-02-26 10:03:02.807] handling notification:  workspace/didChangeConfiguration

[2020-02-26 10:03:02.807] settings  {
  "path": "",
  "debug": true,
  "diagnostics": true,
  "lang": "",
  "use_stdio": false
}

[2020-02-26 10:03:02.807] {
  "path": "",
  "debug": true,
  "diagnostics": true,
  "lang": "",
  "use_stdio": false
}

[2020-02-26 10:03:02.808] received:  Content-Length: 1225

[2020-02-26 10:03:02.820] received payload.

[2020-02-26 10:03:02.821] handling notification:  textDocument/didOpen

[2020-02-26 10:03:02.821] did open: {
  "uri": "file:///Users/ken/.Rprofile",
  "version": 1
}

[2020-02-26 10:03:02.886] received:  Content-Length: 127

[2020-02-26 10:03:02.899] received payload.

[2020-02-26 10:03:02.899] handling request:  textDocument/documentSymbol

[2020-02-26 10:03:02.995] received:  Content-Length: 125

[2020-02-26 10:03:03.006] received payload.

[2020-02-26 10:03:03.006] handling request:  textDocument/documentLink

[2020-02-26 10:03:03.008] received:  Content-Length: 126

[2020-02-26 10:03:03.019] received payload.

[2020-02-26 10:03:03.019] handling request:  textDocument/documentColor

[2020-02-26 10:03:04.268] diagnostics_callback called: {
  "uri": "file:///Users/ken/.Rprofile",
  "version": 1
}

[2020-02-26 10:03:04.272] deliver:  ["Notification", "Message", "R6"]

[2020-02-26 10:03:04.273] method:  textDocument/publishDiagnostics

[2020-02-26 10:03:04.275] parse_callback called: {
  "uri": "file:///Users/ken/.Rprofile",
  "version": 1
}

[2020-02-26 10:03:04.278] document definitions found:  0

[2020-02-26 10:03:04.279] document sections found:  0

[2020-02-26 10:03:04.279] document subsections found:  0

[2020-02-26 10:03:04.280] deliver:  ["Response", "Message", "R6"]

[2020-02-26 10:03:04.282] Error: argument is of length zero
Call: if (!is_absolute_path(start)) {
    start <- path_norm(path(getwd(), start))
}
Stack trace:
1: fs::path_abs(str_texts, rootPath)
2: document_link_reply(id, uri, self$workspace, document, self$rootPath)
3: handler(self, item$id, item$params)
4: parse_callback(self, uri, version, result)
5: private$callback(result)
6: task$check()
7: self$parse_task_manager$check_tasks()
8: self$process_events()

[2020-02-26 10:03:04.283] exiting

[Info  - 10:03:04 AM] Connection to server got closed. Server will restart.
[Error - 10:03:04 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageWriter.fireClose (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:205:15)
	at TCP.<anonymous> (net.js:586:12)
[Error - 10:03:04 AM] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageWriter.fireClose (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/Users/ken/.vscode/extensions/reditorsupport.r-lsp-0.1.5/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:205:15)
	at TCP.<anonymous> (net.js:586:12)
Language server exited with exit code 0
```

**Comment by randy3k** [comment]
Is it a bug introduced in the recent release or it has been here for a while?

**Comment by renkun-ken** [comment]
It has been here for quite a while but ignored because in previous release this error would not cause lsp to exit.
