### ISSUE TITLE
languagerserver not working

### ISSUE THREAD

**Issue by atanasj** [REditorSupport/languageserver#429]
I'm not sure what has happened, but the `languageserver` has stopped working for me. 
This has been tested in both `vscode` and `emacs`. I am getting the following errors from `vscode`:

```
[Error - 10:29:27 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageWriter.fireClose (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
    at Socket.<anonymous> (/Users/atanas/.vscode/extensions/reditorsupport.r-lsp-0.1.14/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
```

And the following in `emacs`:

```
[2021-05-26 10:26:13.660] error handling json:  Error: lexical error: invalid char in json text.
          =====\n## TODO write up bel{"jsonrpc":"2.0","method":"textDo
                     (right here) ------^

Stack trace:
1: parse_string(txt, bigint_as_char)
2: parseJSON(txt, bigint_as_char)
3: parse_and_simplify(txt = txt, simplifyVector = simplifyVector, 
    simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, 
    flatten = flatten, ...)
4: jsonlite::fromJSON(data, simplifyVector = FALSE)
[2021-05-26 10:26:13.675] Error: Unexpected non-empty line
Call: self$read_header()
Stack trace:
1: stop("Unexpected non-empty line")
2: self$read_header()
3: self$fetch(blocking = FALSE)
[2021-05-26 10:26:13.676] exiting

Process lsp-r stderr finished
```
Any help getting to the bottom  of this problem would be greatly appreciated.

**Comment by atanasj** [comment]
Related to local issue on specific file. Issue closed.
